version: "3"

services:
    db:
        image: postgres
        restart: always
        ports:
            - 5432:5432
        environment:
            - POSTGRES_PASSWORD=secret
            - POSTGRES_USER=ppotatoo
            - POSTGRES_DB=bot
        volumes:
            - ~/docker/postgres:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 5s
            timeout: 5s
            retries: 5
    bot:
        build: .
        ports:
            - 81:81
        depends_on:
            db:
                condition: service-healthy
