version: "3"

services:
    db: # postgres service
        image: postgres
        restart: always
        ports:
            - 5432:5432
        environment: #this sets the password and the name of the database, you can change these at will, just remember to change it in the code.
            - POSTGRES_PASSWORD=secret
            - POSTGRES_DB=bot
        volumes: # persistent storage
            - ~/docker/postgres:/var/lib/postgresql/data
        healthcheck: # this is a checker to make sure that the bot does not start before postgres is ready
            test: ["CMD-SHELL", "pg_isready -U postgres -d bot"]
            interval: 5s
            retries: 5
    bot: # the bot service
        build: .
        ports:
            - 81:81 
        depends_on: # this makes it so it fires after postgres is ready
            db:
                condition: service_healthy
